### ISSUE TITLE
Create models in db -1

### ISSUE THREAD

**Issue by christopherjohnson1** [NSS-Day-Cohort-42/rare-talking-heads#112]
## Create in models folder :
- `__init__.py`
- `demotionqueue.py`
- `rareusers.py`
- `subscriptions.py`
- `posts.py`
- `comments.py`
- `reaction.py`
- `postreactions.py`
- `tags.py`
- `posttags.py`
- `categories.py`

Within each file, create models that have the same fields as `https://dbdiagram.io/d/5f885a013a78976d7b77cb74` ERD

- run `python manage.py makemigrations rareserverapi`
- run `python manage.py migrate`

- make sure you make a connection to your database.

**Comment by meesterbaumer** [comment]
Rated 1
Expected time 1hr.
Actual time 1.5 hrs.
